--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Hu4wh1/PiggyCrates
branches:
- master
projects: 
  PiggyCrates:
    path: ""
    lib:
      - src: CortexPE/Commando/Commando
        version: ^0.5
...
